### ISSUE TITLE
Error botón acción en Android (incidencia repetida)

### ISSUE THREAD

**Issue by gabrielgt** [CKGrafico/Cordova-Multiplatform-Template#16]
En la incidencia anterior que creé al respecto después de que la marcaras como cerrada puse este comentario que creo que no has visto:

Creo que ya he encontrado el problema. En el fichero actions.html sobra la clase button-calm:

```
<ion-view view-title="Actions">
    <ion-nav-buttons side="right">
        <button class="button button-clear BUTTON-CALM icon icon-only ion-ionic" ng-click="vm.exampleAction()"></button>
    </ion-nav-buttons>
...
```
Con ese cambio ya me funciona bien en todos los entornos. Pero me quedo con tres dudas:
1. ¿Por qué en el emulador de Android se veía bien?
2. ¿Por qué a ti se te ve bien en el simulador Ripple con Android?
3. ¿Qué branch está subida a la Visual Studio Gallery?

**Comment by CKGrafico** [comment]
Hola, esa clase está bien te explico.
En Windows y en iOS queremos que ese botón sea del color de la app, en este caso 'calm' pero en android queremos que sea blanco por eso si vas a merges/android/css/platform.css ves esta línea
ion-header-bar .buttons-right .right-buttons .button {
    color: #FFF !important;
}

**Comment by gabrielgt** [comment]
Hola, muchas gracias por la explicación y por tu paciencia ;-)

Debe ser lo que tú dices, que no me está cogiendo el css de android.
Probando con el inspector de elementos de Chrome veo lo siguiente:

```css
.button.button-calm.button-clear {
    border-color: transparent;
    background: none;
    box-shadow: none;
    color: #1AA8D0;
}
.bar-calm .button.button-clear {
    border-color: transparent;
    background: none;
    box-shadow: none;
    color: #fff;
    font-size: 17px;
}
```

El fichero www/css/platform.css está vacío después de que se ejecuta la tarea default:css.
Si copio el contenido del platform.css de android a www y desactivo la tarea default:css entonces sí me funciona correctamente, y veo con el inspector de elementos lo siguiente:

```css
ion-header-bar .buttons-right .right-buttons .button {
    color: #FFF !important;
}
```

Supongo que el problema estará relacionado con lo que te conté de que tuve que poner esto en el gulpfile.js para que me funcionara la tarea default:css:

```js
var promise = require('es6-promise').polyfill();
```

Pero no sé porque no me funciona la librería gulp-autoprefixer si no pongo eso.
